version: 2.1

orbs:
  ci-caching: jobcloud/ci-caching@0.5

workflows:
  version: 2
  test-messaging-lib:
    jobs:
      - ci-caching/build-docker-images:
          dockerComposeFile: "./docker/docker-compose.yml"
      - install-dependencies:
          requires:
            - ci-caching/build-docker-images
      - coverage:
          requires:
            - install-dependencies
      - code-style:
          requires:
            - install-dependencies
      - static-analysis:
          requires:
            - install-dependencies

jobs:
  install-dependencies:
    machine: true
    steps:
      - checkout
      - ci-caching/run-docker-from-restored-caches:
          dependencyCheckSumFile: "./composer.lock"
          dockerComposeFile: "./docker/docker-compose.yml"
      - ci-caching/dependency-check:
          cacheDataPath: "./composer.lock"
      - ci-caching/execute-in-container:
          dockerComposeFile: "./docker/docker-compose.yml"
          info: Install dependencies
          command: make install-dependencies
          container: php
      - ci-caching/dependency-cache-save:
          checkSumFile: "./composer.lock"
          cacheDataPath: "./vendor"

  coverage:
    machine: true
    steps:
      - ci-caching/run-docker-from-restored-caches:
          dependencyCheckSumFile: "./composer.lock"
          dockerComposeFile: "./docker/docker-compose.yml"
      - ci-caching/execute-in-container:
          dockerComposeFile: "./docker/docker-compose.yml"
          info: Execute tests with code coverage
          command: make coverage
          container: php
      - store_artifacts:
          path: ./build/logs/phpunit/coverage
      - store_test_results:
          path: ./build/logs/phpunit

  code-style:
    machine: true
    steps:
      - ci-caching/run-docker-from-restored-caches:
          dependencyCheckSumFile: "./composer.lock"
          dockerComposeFile: "./docker/docker-compose.yml"
      - ci-caching/execute-in-container:
          dockerComposeFile: "./docker/docker-compose.yml"
          info: Check code style
          command: make code-style
          container: php
      - store_test_results:
          path: ./build/logs/phpcs

  static-analysis:
    machine: true
    steps:
      - ci-caching/run-docker-from-restored-caches:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.lock"
      - ci-caching/execute-in-container:
          dockerComposeFile: "./docker/docker-compose.yml"
          info: Execute static analysis
          command: make static-analysis
          container: php
      - store_test_results:
          path: ./build/logs/phpstan
  infection-testing:
    machine: true
    steps:
      - ci-caching/run-docker-from-restored-caches:
          dockerComposeFile: "./docker/docker-compose.yml"
          dependencyCheckSumFile: "./composer.lock"
      - ci-caching/execute-in-container:
          dockerComposeFile: "./docker/docker-compose.yml"
          info: Execute infection testing
          command: make infection-testing
          container: php